### ISSUE TITLE
Use ASP3.0 ERROR

### ISSUE THREAD

**Issue by bfspy2016** [BF2Statistics/BattleSpy#2]
Congratulations on your new work. I just tested it and found several problems.

Lack of "rank" field in "player" table of database prevents new account registration

**Comment by bfspy2016** [comment]
request:
I'm really sorry. I tried many times and failed all the time.
I set up a table "m_servers"  in the database to join the  manual servers with 23 necessary fields, such as country hostname GameName gamever, etc.
When players access theserverlist, I want to add the servers in the "m_servers" to the servers in the array and send them to the client.
This codes in masterclient.cs 
Stream.SendAsync(
                Enctypex.Encode(
                    Encoding.UTF8.GetBytes("hW6m9a"), 
                    Encoding.UTF8.GetBytes(validate),
                    unencryptedServerList,
                    unencryptedServerList.LongLength
                )
            );
list ms = new list ();
using (MasterDatabase Driver = new MasterDatabase())
                        {
                           m_servers = Driver.Query("SELECT * FROM m_servers");
                          while true
                           {
                           ms.Add().................................
                            }

                           .........................
                          list ms  to byte[] unencryptedServerList_m
byte[] unencryptedServerList =   sum unencryptedServerList and  unencryptedServerList_m

Can this be achieved? heartfelt thanks!!!

**Comment by wilson212** [comment]
Why are you changing the table names? This is not supported D:

**Comment by wilson212** [comment]
This is quite the task. Is it possible? Yes, but it will take quite a bit of coding
